//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnagMe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SnagMeEntities : DbContext
    {
        public SnagMeEntities()
            : base("name=SnagMeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applicant> Applicants { get; set; }
        public virtual DbSet<ApplicantQA> ApplicantQAs { get; set; }
        public virtual DbSet<QA> QAs { get; set; }
        public virtual DbSet<vw_GetAppliantQA> vw_GetAppliantQA { get; set; }
    }
}
